# Generated by Django 4.2 on 2025-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importance", models.IntegerField(default=5)),
                ("dependencies", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("smart_balance", "Smart Balance"),
                            ("high_impact", "High Impact"),
                            ("fastest_wins", "Fastest Wins"),
                            ("deadline_driven", "Deadline Driven"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("importance", models.IntegerField()),
                ("estimated_hours", models.FloatField()),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
